import type { CommunityPost, Event, MerchandiseProduct, TicketType } from "@/types/domain";

export const featuredEvents: Event[] = [
  {
    id: "event-1",
    slug: "neon-rooftop-sessions",
    title: "Neon Rooftop Sessions",
    description: "A premium rooftop party with local DJs, signature cocktails, and late-night skyline views.",
    venue: "Skyline Social Club",
    city: "Cape Town",
    startsAt: "2026-06-12T20:00:00Z",
    category: "party",
    minPrice: 180,
    currency: "ZAR",
    status: "published",
    tags: ["DJ", "Rooftop", "Cocktails"],
  },
  {
    id: "event-2",
    slug: "karaoke-after-dark",
    title: "Karaoke After Dark",
    description: "Bring your crew for themed karaoke rounds, prizes, and crowd-voted performances.",
    venue: "The Velvet Room",
    city: "Johannesburg",
    startsAt: "2026-06-18T19:30:00Z",
    category: "karaoke",
    minPrice: 90,
    currency: "ZAR",
    status: "published",
    tags: ["Karaoke", "Prizes", "Crew Night"],
  },
  {
    id: "event-3",
    slug: "beer-pong-city-cup",
    title: "Beer Pong City Cup",
    description: "Tournament-style beer pong with team entries, brackets, food stalls, and live hosts.",
    venue: "District Warehouse",
    city: "Durban",
    startsAt: "2026-06-27T18:00:00Z",
    category: "games",
    minPrice: 120,
    currency: "ZAR",
    status: "published",
    tags: ["Beer Pong", "Tournament", "Food"],
  },
];

export const ticketTypes: TicketType[] = [
  {
    id: "ticket-1",
    eventId: "event-1",
    name: "General Access",
    description: "Entry to the main rooftop event area.",
    price: 180,
    currency: "ZAR",
    quantityAvailable: 250,
    quantitySold: 82,
  },
  {
    id: "ticket-2",
    eventId: "event-1",
    name: "VIP Lounge",
    description: "Priority entry and lounge access. Payment integration will be added later.",
    price: 420,
    currency: "ZAR",
    quantityAvailable: 50,
    quantitySold: 14,
  },
];

export const merchandiseProducts: MerchandiseProduct[] = [
  {
    id: "merch-1",
    name: "NightEvents Black Tee",
    slug: "nightevents-black-tee",
    description: "Heavy cotton event tee with reflective chest branding.",
    price: 320,
    currency: "ZAR",
    inventoryCount: 80,
    isActive: true,
  },
  {
    id: "merch-2",
    name: "Afterparty Cap",
    slug: "afterparty-cap",
    description: "Low-profile cap for day-after recovery missions.",
    price: 260,
    currency: "ZAR",
    inventoryCount: 45,
    isActive: true,
  },
  {
    id: "merch-3",
    name: "VIP Wristband Pack",
    slug: "vip-wristband-pack",
    description: "Collectible wristbands for crews and event loyalty campaigns.",
    price: 140,
    currency: "ZAR",
    inventoryCount: 120,
    isActive: true,
  },
];

export const communityPosts: CommunityPost[] = [
  {
    id: "post-1",
    authorId: "user-1",
    authorName: "Lebo M.",
    title: "Best rooftop set this month?",
    excerpt: "The skyline stage was unreal. Drop your top tracks from the night so we can build a shared playlist.",
    eventId: "event-1",
    createdAt: "2026-05-02T10:00:00Z",
    commentCount: 18,
    reactionCount: 74,
  },
  {
    id: "post-2",
    authorId: "user-2",
    authorName: "Amara K.",
    title: "Karaoke theme ideas",
    excerpt: "Should the next karaoke night be 2000s R&B, local classics, or guilty pleasure pop?",
    createdAt: "2026-05-04T12:30:00Z",
    commentCount: 11,
    reactionCount: 39,
  },
  {
    id: "post-3",
    authorId: "user-3",
    authorName: "Josh T.",
    title: "Beer pong team finder",
    excerpt: "Looking for one more teammate for City Cup. Must be calm under pressure and good with trick shots.",
    eventId: "event-3",
    createdAt: "2026-05-05T16:45:00Z",
    commentCount: 7,
    reactionCount: 22,
  },
];
